### ISSUE TITLE
Help with the tun echo example 

### ISSUE THREAD

**Issue by Archieeeeee** [google/netstack#8] opened 2018-06-04 19:44 UTC
Hello,
I have followed the doc but do not see the port being listened:
> $ sudo ip tuntap add mode tun tun0
> $ sudo ip link set tun0 up
> $ sudo ip addr add 192.168.1.1/24 dev tun0
> $ ./tun_tcp_echo tun0 192.168.1.1 9999

but  port 9999 is not listened as expected
> $ netstat -lnp
>Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      15505/sshd          
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1298/master         
udp        0      0 127.0.0.1:323           0.0.0.0:*                           15939/chronyd       
udp6       0      0 ::1:323                 :::*                                15939/chronyd       
Active UNIX domain sockets (only servers)...

here's my tun0 state
> $ ip addr show dev tun0
>7: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 500
    link/none 
    inet 192.168.1.1/24 scope global tun0
       valid_lft forever preferred_lft forever

btw, I'm running the example on latest CentOS 7

**Comment by antong** [comment] 2018-09-07 04:43
This is a user space network stack entirely within the `tun_tcp_echo` process. Netstat shows info from your Linux host's network stack.

**Comment by amscanne** [comment] 2019-02-26 00:47
I agree with antong@, so I'm closing as works as intended. Please reopen if there's any miscommunication here.

**Closed by amscanne** 2019-02-26 00:47 UTC
